# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [1]:
import numpy as np

In [14]:
# Generate some random data.
data = np.random.randn(3, 3)

In [15]:
data

array([[ 1.17894382, -0.10952043,  2.54023812],
       [-0.22796439,  0.0885731 ,  0.33403476],
       [ 0.97499458, -1.97950916, -0.54759828]])

In [16]:
data * 10

array([[ 11.78943822,  -1.09520429,  25.40238119],
       [ -2.27964387,   0.88573098,   3.34034758],
       [  9.74994584, -19.79509159,  -5.47598281]])

In [17]:
data + data

array([[ 2.35788764, -0.21904086,  5.08047624],
       [-0.45592877,  0.1771462 ,  0.66806952],
       [ 1.94998917, -3.95901832, -1.09519656]])

In [18]:
data.shape

(3, 3)

In [19]:
data.dtype

dtype('float64')

## Creating ndarrays

In [20]:
data1 = [6, 7.5, 8, 0, 1]

In [21]:
arr1 = np.array(data1)

In [22]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [24]:
arr2 = np.array(data2)

In [25]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.ndim #ndim = n dimensional

2

In [27]:
arr2.shape # returns the shape of arr in (row, column)

(2, 4)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [33]:
np.zeros(10) # zeros() will create array with default 0 values.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
np.empty((2, 3, 2))

array([[[6.23042070e-307, 3.56043053e-307],
        [1.60219306e-306, 7.56571288e-307],
        [1.89146896e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [9.79097007e-307, 1.60221208e-306],
        [8.34443015e-308, 1.32448022e+165]]])

In [51]:
np.arange(15) # arange is like range() in classical python.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

In [52]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [53]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [54]:
arr1.dtype # with the help of dtype we can check the data type.

dtype('float64')

In [55]:
arr2.dtype

dtype('int32')

In [56]:
arr = np.array([1, 2, 3, 4, 5])

In [57]:
arr.dtype

dtype('int32')

In [58]:
float_arr = arr.astype(np.float64)

In [59]:
float_arr.dtype

dtype('float64')

In [60]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [61]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [71]:
arr.astype(np.int64) # astype() method will convert according to the argument type.

array([ 3, -1, -2,  0, 12, 10], dtype=int64)

In [74]:
numeric_strings = np.array(['0.25', '2.5', '-9.6'], dtype=np.string_)

In [76]:
numeric_strings.astype(float)

array([ 0.25,  2.5 , -9.6 ])

In [77]:
int_array = np.arange(10)

In [78]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [79]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Arithmatic with NumPy Arrays

In [80]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [81]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [82]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [83]:
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [84]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [86]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [87]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [88]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [89]:
arr1 > arr2

array([[ True, False,  True],
       [False, False, False]])

In [90]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [2]:
arr = np.arange(10);

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5:8]

array([5, 6, 7])

In [5]:
arr[5:8] = 12

In [6]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr1 = np.arange(20);

In [8]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
arr1[10:16]

array([10, 11, 12, 13, 14, 15])

In [13]:
arr1[10:16] = 55

In [14]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 55, 55, 55, 55, 55, 55, 16,
       17, 18, 19])

In [15]:
arr_slice = arr[5:8]

In [16]:
arr_slice

array([12, 12, 12])

In [17]:
arr_slice[1] = 12345

In [18]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [19]:
arr_slice[:] = 64

In [20]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [22]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]);

In [23]:
arr2d[2]

array([7, 8, 9])

In [24]:
arr2d[0][2]

3

In [25]:
arr2d[0, 2]

3

In [26]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]]);

In [27]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr3by3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]]);

In [30]:
arr3by3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [31]:
arr3by3[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [32]:
arr3by3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr3by3[2]

array([[13, 14, 15],
       [16, 17, 18]])

In [34]:
old_values = arr3by3[0].copy();

In [35]:
arr3by3[0] = 42

In [36]:
arr3by3[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [37]:
arr3by3

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [38]:
arr3by3[1, 0]

array([7, 8, 9])

In [39]:
arr3by3[1, 1]

array([10, 11, 12])

In [40]:
x = arr3by3[1]

In [41]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
x[0]

array([7, 8, 9])

In [43]:
x[1]

array([10, 11, 12])

## Indexing with slices

In [44]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [45]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [58]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [57]:
arr2d[:2] #2nd index sudhinu.

array([[1, 0, 0],
       [4, 0, 0]])

In [49]:
arr2d[:1] #1st index sudhinu.

array([[1, 2, 3]])

In [50]:
arr2d[:2, 1:] # 2nd index sudhinu and first column pachhinu.

array([[2, 3],
       [5, 6]])

In [51]:
arr2d[1, :2] # only 1st index nu and column with 2nd index pehla nu

array([4, 5])

In [53]:
arr2d[:, :1] # baddha j elements but 1st index pehlana

array([[1],
       [4],
       [7]])

In [54]:
arr2d[:2, 1:] = 0

In [55]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [4]:
import numpy as np
names = np.array(['Bob', 'Joe', 'will', 'Bob', 'will', 'Joe', 'Joe'])

In [5]:
data = np.random.randn(7, 4)

In [6]:
names

array(['Bob', 'Joe', 'will', 'Bob', 'will', 'Joe', 'Joe'], dtype='<U4')

In [7]:
data

array([[-0.28005478,  0.53354182,  0.2870872 , -0.78369121],
       [-0.44254859,  0.46969791,  1.09318601,  2.28978983],
       [-0.52830174,  1.61440774,  0.18916267, -0.55853289],
       [-0.79130079,  0.01936274,  0.65972023,  0.61055662],
       [ 0.1477846 ,  0.43548199, -0.92897305,  1.53622557],
       [-0.64438118,  1.02109902, -1.20265083, -0.54754005],
       [ 0.06141615,  1.12861646, -1.29466328,  0.31490614]])

In [8]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [10]:
names == 'Joe'

array([False,  True, False, False, False,  True,  True])

In [18]:
data[names == 'Bob']
# data[0:2]

array([[-0.28005478,  0.53354182,  0.2870872 , -0.78369121],
       [-0.79130079,  0.01936274,  0.65972023,  0.61055662]])

In [20]:
data[names == 'Bob', 2:] # true thi true sudhi and index number 2 pachhina baddha j

array([[ 0.2870872 , -0.78369121],
       [ 0.65972023,  0.61055662]])

In [21]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [22]:
data[~(names == "Bob")]

array([[-0.44254859,  0.46969791,  1.09318601,  2.28978983],
       [-0.52830174,  1.61440774,  0.18916267, -0.55853289],
       [ 0.1477846 ,  0.43548199, -0.92897305,  1.53622557],
       [-0.64438118,  1.02109902, -1.20265083, -0.54754005],
       [ 0.06141615,  1.12861646, -1.29466328,  0.31490614]])

In [24]:
cond = names == "Bob"

In [26]:
data[~cond]

array([[-0.44254859,  0.46969791,  1.09318601,  2.28978983],
       [-0.52830174,  1.61440774,  0.18916267, -0.55853289],
       [ 0.1477846 ,  0.43548199, -0.92897305,  1.53622557],
       [-0.64438118,  1.02109902, -1.20265083, -0.54754005],
       [ 0.06141615,  1.12861646, -1.29466328,  0.31490614]])

In [27]:
mask = (names == "Bob") | (names == "will")

In [28]:
mask

array([ True, False,  True,  True,  True, False, False])

In [29]:
data[mask]

array([[-0.28005478,  0.53354182,  0.2870872 , -0.78369121],
       [-0.52830174,  1.61440774,  0.18916267, -0.55853289],
       [-0.79130079,  0.01936274,  0.65972023,  0.61055662],
       [ 0.1477846 ,  0.43548199, -0.92897305,  1.53622557]])

In [30]:
data[data < 0] = 0

In [31]:
data

array([[0.        , 0.53354182, 0.2870872 , 0.        ],
       [0.        , 0.46969791, 1.09318601, 2.28978983],
       [0.        , 1.61440774, 0.18916267, 0.        ],
       [0.        , 0.01936274, 0.65972023, 0.61055662],
       [0.1477846 , 0.43548199, 0.        , 1.53622557],
       [0.        , 1.02109902, 0.        , 0.        ],
       [0.06141615, 1.12861646, 0.        , 0.31490614]])

In [32]:
data[names != "Joe"] = 7

In [33]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.46969791, 1.09318601, 2.28978983],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.02109902, 0.        , 0.        ],
       [0.06141615, 1.12861646, 0.        , 0.31490614]])

## Fancy Slicing

In [34]:
arr = np.empty((8, 4))

In [35]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
for i in range(8):
    arr[i] = i

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [41]:
arr[[-3,  -5, -7]] # chhellethi 3ju, chhellethi 5mu, and chhellethi 7mu

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [42]:
arr = np.arange(32).reshape((8, 4))

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [44]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] #[1, 5, 7, 2] row uthavo and pacchi [0, 3, 1, 2] columna element uthavo.

array([ 4, 23, 29, 10])

In [49]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [50]:
arr = np.arange(15).reshape((3, 5))

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
arr.T # Transposing arrays with T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [53]:
arr = np.random.randn(6, 3)

In [54]:
arr

array([[ 0.59834939, -0.18136302,  0.30372291],
       [ 0.54275835, -0.78372153, -0.64653684],
       [ 1.54984354,  1.79860484,  1.63499939],
       [ 0.0621349 , -0.44946858,  1.19883781],
       [-1.12774222,  1.34654457,  0.09490344],
       [ 0.68121041,  0.24536365, -2.89194229]])

In [55]:
np.dot(arr.T, arr)

array([[ 4.7943345 ,  0.87432765,  0.36225426],
       [ 0.87432765,  5.95749895,  2.27171284],
       [ 0.36225426,  2.27171284, 12.99302948]])

In [58]:
arr = np.arange(16).reshape(2, 2, 4) # 2 array banavo 2X4 na

In [59]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr.transpose(1, 0, 2) # 2nd index will be 1st, and 1st index will be 2nd.

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [65]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [74]:
arr.swapaxes(1, 2) # Swap aray without changing it.

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [70]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# End of 4.1