In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
x = np.random.randn(8)

In [8]:
y = np.random.randn(8)

In [9]:
x

array([-1.47338184,  0.16338223, -1.33961116, -0.95451903, -1.23670248,
        0.27176688,  0.24345229,  1.00819702])

In [10]:
y

array([-1.25709396, -0.57329764, -0.70014859, -0.18206399, -0.11572346,
       -0.35399712, -0.58013351, -0.90674786])

In [12]:
np.maximum(x, y) # here np.maximum computed the element wise maximum from x and y.

array([-1.25709396,  0.16338223, -0.70014859, -0.18206399, -0.11572346,
        0.27176688,  0.24345229,  1.00819702])

In [19]:
arr = np.random.randn(7) * 5

In [20]:
arr

array([-0.43577116, 10.0626785 ,  6.45655222, -2.22450927,  0.01870634,
        0.82102409,  1.15480342])

In [21]:
remainder, whole_part = np.modf(arr)

In [22]:
remainder

array([-0.43577116,  0.0626785 ,  0.45655222, -0.22450927,  0.01870634,
        0.82102409,  0.15480342])

In [23]:
whole_part

array([-0., 10.,  6., -2.,  0.,  0.,  1.])

In [24]:
arr

array([-0.43577116, 10.0626785 ,  6.45655222, -2.22450927,  0.01870634,
        0.82102409,  1.15480342])

In [25]:
np.sqrt(arr)

<ipython-input-25-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 3.17217252, 2.54097466,        nan, 0.13677112,
       0.9061038 , 1.0746178 ])

In [26]:
np.sqrt(arr, arr)

<ipython-input-26-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan, 3.17217252, 2.54097466,        nan, 0.13677112,
       0.9061038 , 1.0746178 ])

In [27]:
arr

array([       nan, 3.17217252, 2.54097466,        nan, 0.13677112,
       0.9061038 , 1.0746178 ])

In [28]:
np.abs(arr)

array([       nan, 3.17217252, 2.54097466,        nan, 0.13677112,
       0.9061038 , 1.0746178 ])

In [29]:
np.fabs(arr)

array([       nan, 3.17217252, 2.54097466,        nan, 0.13677112,
       0.9061038 , 1.0746178 ])

In [30]:
np.sqrt(arr)

array([       nan, 1.78105938, 1.59404349,        nan, 0.3698258 ,
       0.95189484, 1.03663774])

In [31]:
np.square(arr)

array([        nan, 10.0626785 ,  6.45655222,         nan,  0.01870634,
        0.82102409,  1.15480342])

In [32]:
np.exp(arr)

array([        nan, 23.85926281, 12.69203535,         nan,  1.1465657 ,
        2.47466194,  2.92887328])

In [33]:
np.log(arr)

array([        nan,  1.15441669,  0.93254773,         nan, -1.98944637,
       -0.09860142,  0.07196507])

In [34]:
np.log10(arr)

array([        nan,  0.5013568 ,  0.40500033,         nan, -0.86400558,
       -0.04282205,  0.03125403])

In [35]:
np.add(x, y)

array([-2.7304758 , -0.40991541, -2.03975975, -1.13658303, -1.35242595,
       -0.08223025, -0.33668122,  0.10144916])

In [37]:
np.divide(x, y)

array([ 1.17205387, -0.28498675,  1.91332409,  5.24276665, 10.6867048 ,
       -0.76770928, -0.41964873, -1.11188244])

In [38]:
np.floor_divide(x, y)

array([ 1., -1.,  1.,  5., 10., -1., -1., -2.])

In [40]:
np.power(x, y)

<ipython-input-40-56b38dfee6de>:1: RuntimeWarning: invalid value encountered in power
  np.power(x, y)


array([       nan, 2.82532117,        nan,        nan,        nan,
       1.5859621 , 2.26966562, 0.99262499])