In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.],[4., 5., 6.]]) # 2X3 matrix

In [6]:
y = np.array([[6., 23.], [-1, 7], [8, 9]]) # 3X2 matrix

In [7]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [8]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [9]:
x.dot(y) # dot production method 1

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
np.dot(x, y) # dot production method 2

array([[ 28.,  64.],
       [ 67., 181.]])

In [11]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [14]:
x @ np.ones(3) # @ symbol represents a matrix multiplication.

array([ 6., 15.])

In [15]:
from numpy.linalg import inv, qr

In [32]:
x = np.random.randn(5, 5)

In [42]:
mat = x.T.dot(x) # x*x transpose

In [43]:
mat

array([[ 1.52257963,  0.99438635, -0.7274153 ,  0.58561177, -1.51225828],
       [ 0.99438635,  1.94060506, -2.031998  , -0.99857013, -0.65662659],
       [-0.7274153 , -2.031998  ,  3.67827913,  2.02314373, -0.12594064],
       [ 0.58561177, -0.99857013,  2.02314373,  2.111922  , -1.36068501],
       [-1.51225828, -0.65662659, -0.12594064, -1.36068501,  4.12074226]])

In [44]:
inv(mat)

array([[ 8.14574761, -5.02732949,  3.12710957, -7.8246183 , -0.29985245],
       [-5.02732949,  4.59516864, -1.24382686,  5.10236622,  0.53406742],
       [ 3.12710957, -1.24382686,  2.27768681, -3.78610135, -0.23116478],
       [-7.8246183 ,  5.10236622, -3.78610135,  9.24967703,  0.88007893],
       [-0.29985245,  0.53406742, -0.23116478,  0.88007893,  0.50127515]])

In [45]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  5.55111512e-16,  1.11022302e-16,
        -1.11022302e-15,  0.00000000e+00],
       [ 7.49400542e-16,  1.00000000e+00,  8.32667268e-16,
         1.22124533e-15,  1.66533454e-16],
       [-2.24126273e-15, -6.38378239e-16,  1.00000000e+00,
        -2.22044605e-15, -1.52655666e-16],
       [ 2.10942375e-15, -6.66133815e-16, -4.99600361e-16,
         1.00000000e+00,  0.00000000e+00],
       [-1.33226763e-15, -2.22044605e-15,  8.88178420e-16,
         1.33226763e-15,  1.00000000e+00]])

In [46]:
q, r = qr(mat)

In [47]:
q

array([[-0.59877052,  0.10716099,  0.15256017,  0.73817012, -0.2486376 ],
       [-0.39105294, -0.46075584, -0.66136527,  0.03553503,  0.44284862],
       [ 0.28606375,  0.58878274, -0.69555349,  0.22575616, -0.1916818 ],
       [-0.23029801,  0.60889151,  0.19685323, -0.07007997,  0.72976131],
       [ 0.59471154, -0.24250072,  0.12952035,  0.63084474,  0.41565727]])

In [48]:
r

array([[-2.54284333, -2.09610421,  1.74157162, -0.67699172,  3.89026043],
       [ 0.        , -2.43277948,  4.28642739,  3.32994233, -1.76145474],
       [ 0.        ,  0.        , -0.94357108, -0.41794179,  0.55702285],
       [ 0.        ,  0.        ,  0.        , -0.15285036,  1.52683637],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.82919984]])